### ISSUE TITLE
Allow writing of drift-corrected images as part of pipeline

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#151]
@josephneos1010 @TLSteinacker 

Would be opt-in either from CLI invocation of pipeline or from config file

**Comment by TLSteinacker** [comment]
either would be fine; probably easier to use for people in the lab if it becomes part of the config file

**Comment by vreuter** [comment]
> either would be fine; probably easier to use for people in the lab if it becomes part of the config file

protocol for this sort of thing (i.e., the [least surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) behavior) is often to have CLI override the config if specified, otherwise deferring to a config value, possible with a default. @TLSteinacker @josephneos1010 what do you think?

**Comment by vreuter** [comment]
Closing in favor of #288
