### ISSUE TITLE
Enhancement ideas for locus-specific spot visualisation

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#259]
Follow-up of #64 / #192

- [x] ⚠️ wait for #214 
- [x] ⚠️ wait for #215 
- [ ] #269
- [x] #268 
- [x] #265

**Comment by vreuter** [comment]
@TLSteinacker  WDYT?

**Comment by TLSteinacker** [comment]
Sounds like a really good idea!

**Comment by vreuter** [comment]
Enabled by #115

**Comment by vreuter** [comment]
This has been handled by a plugin.
