### ISSUE TITLE
Enhancement ideas for regional spot visualisation

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#260]
- [ ] scrollable data in `napari`, like locus-specific spots
- [ ] boxes (perhaps colored or dashed by overall acceptance status), and text labels to describe why discarded

Follow-up of #63 / #192

Make the stoppability of the pipeline for interactive visualisation configurable. The CLI program supports image saving and/or interactivity, but the pipeline invocation of this provides no config file hook for allowing the user to say the pipeline should stop for spot visualisation, rather than simply saving the images.

**Comment by vreuter** [comment]
@TLSteinacker WDYT about config for this? 

__TL;DR__

To summarise, I favor something like...
```yaml
regional_spot_visualisation:
    save_projections: True
    interact: False
```
where it would be skipping the step if both are `False`

There are three possible use modes:
a) save 2D projections, no interactivity (current pipeline setup)
b) save 2D projections but also do interactive vis
c) only interactive vis

The CLI for the program to run to do this also supports only using a subset of positions, which in theory could also be configurable, but I wouldn't favor it necessarily. In any case, for the interactive use, the user is going to need to invoke the CLI program anyway, so could specify directly the positions to use by that interface.

**Comment by TLSteinacker** [comment]
This looks really good. I like the idea that the interactive visualisation can be switched on/off in the config file as we might need it whenever we start a new experiment series with new oligo probes, but then the intensity values should remain quite comparable throughout all experiments with these oligos probes.
