### ISSUE TITLE
Need to discard data from FOVs with no beads for drift correction in reference timepoint

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#285]
Encountered recently w/ @TLSteinacker

**Comment by vreuter** [comment]
This is a follow-up of #222 , where while we "tolerate" the lack of sufficient bead ROIs for drift correction in that we don't crash during the partition phase when there are too few ROIs, we haven't yet encountered this when there's an absence of sufficient ROIs in the _reference_ timepoint _and_ we proceed to the next step, where we're trying to do drift correction of all data, but we're lacking the partition files (shifting and accuracy) for a particular FOV, due to the absence of bead ROIs in the reference timepoint for that FOV (which is the same as for all other FOVs).

**Comment by vreuter** [comment]
Underscoring the ZARR seems to work to get the data to be ignore for nuclear image / mask creation, but then the numbering/naming of the fields of view is wrong. Here's an example, and how it messes up the visualisation in `napari` of the nuclear masks.

```console
$ ls -1 nuc_images_zarr
P0001.zarr
P0002.zarr
P0003.zarr
P0004.zarr
P0005.zarr
P0006.zarr
P0007.zarr
P0008.zarr
P0009.zarr
P0010.zarr
P0011.zarr
P0012.zarr
P0013.zarr
P0014.zarr
_P0015.zarr
P0016.zarr
P0017.zarr
P0018.zarr
P0019.zarr
P0020.zarr
P0021.zarr
P0022.zarr
P0023.zarr
P0024.zarr
P0025.zarr
P0026.zarr
P0027.zarr
P0028.zarr
P0029.zarr
P0030.zarr
$
$
$ ls -1 nuc_images
P0001.zarr
P0002.zarr
P0003.zarr
P0004.zarr
P0005.zarr
P0006.zarr
P0007.zarr
P0008.zarr
P0009.zarr
P0010.zarr
P0011.zarr
P0012.zarr
P0013.zarr
P0014.zarr
P0016.zarr
P0017.zarr
P0018.zarr
P0019.zarr
P0020.zarr
P0021.zarr
P0022.zarr
P0023.zarr
P0024.zarr
P0025.zarr
P0026.zarr
P0027.zarr
P0028.zarr
P0029.zarr
P0030.zarr
$
$
$ ls -1 nuc_masks/
P0001.zarr
P0002.zarr
P0003.zarr
P0004.zarr
P0005.zarr
P0006.zarr
P0007.zarr
P0008.zarr
P0009.zarr
P0010.zarr
P0011.zarr
P0012.zarr
P0013.zarr
P0014.zarr
P0015.zarr
P0016.zarr
P0017.zarr
P0018.zarr
P0019.zarr
P0020.zarr
P0021.zarr
P0022.zarr
P0023.zarr
P0024.zarr
P0025.zarr
P0026.zarr
P0027.zarr
P0028.zarr
P0029.zarr
```

<img width="725" alt="Screenshot 2024-07-11 at 12 51 28" src="https://github.com/gerlichlab/looptrace/assets/12036370/7be92010-2916-4512-bb41-733ae40ba30a">

**Comment by vreuter** [comment]
@TLSteinacker can this be closed based on recent experience when we've needed to remove data from 1-3 (IIRC) FOVs? The nuclear masks were initially wrong as outlined here, but I believe this has been resolved.

**Comment by TLSteinacker** [comment]
Yes, I think so too. I haven't had this issue in a long time.
